const ALERT_SUCCESS = 'REGISTRO EXECUTADO COM SUCESSO.';
const ALERT_ERROR = 'OPS! OCORREU ALGUM ERRO';
const ALERT_WARNING = '';

const ALERT_CUSTOM = (message: string) => message;

export { ALERT_SUCCESS, ALERT_ERROR, ALERT_WARNING, ALERT_CUSTOM };
